UTIL: Filter Class Reference
Filter Class Reference
Class to do fastq read filter by various standards and methods.
#include <filter.h>
Public Member Functions
Filter (int lowQualThreshold, int maxLowQualNum, int maxNBaseNum, double minComplexity, int minLen, int maxLen)
Construct a Filter object, negative parameter will turn the corresponding filterr.
~Filter ()=default
Destroy a Filter object.
int passFilter (Read *r)
Test whether a Read pass filter.
bool passLowComplexityFliter (Read *r)
Test whether a Read pass low complexity filter.
Static Public Member Functions
static bool filterByIndex (Read *r, const std::vector< std::string > &indexBlackList, const int &threshold)
Filter a Read by its first index.
static bool filterByIndex (Read *r1, Read *r2, const std::vector< std::string > &indexBlackList, const int &threshold)
Filter a pair of Read by their first index.
static bool match (const std::vector< std::string > &list, const std::string &target, int threshold)
match a sequnce (target) against a series of sequences (list)
static Read * trimAndCut (Read *r, int forceFrontCut, int forceTailCut, QualCutOpt *opt)
Trim and cut a Read by various methods.
Detailed Description
Class to do fastq read filter by various standards and methods.
Definition at line 27 of file filter.h.
Constructor & Destructor Documentation
Filter()
Filter::Filter (int lowQualThreshold, int maxLowQualNum, int maxNBaseNum, double minComplexity, int minLen, int maxLen) inline
Construct a Filter object, negative parameter will turn the corresponding filterr.
Parameters
lowQualThreshold low quality threshold, if set to negative number
maxLowQualNum maximum low quality bases allowed for a sequence
maxNBaseNum maximum N bases allowed for a sequence
minComplexity minimum complexity allowed for a sequence
minLen minimum length required for a sequence
maxLen maximum length allowed for a sequence
Definition at line 43 of file filter.h.
{
             this->lowQualThreshold = lowQualThreshold;
             this->maxLowQualNum = maxLowQualNum;
             this->maxNBaseNum = maxNBaseNum;
             this->minComplexity = minComplexity;
             this->minLen = minLen;
             this->maxLen = maxLen;
         }
Member Function Documentation
filterByIndex() [1/2]
static bool Filter::filterByIndex (Read * r, const std::vector< std::string > & indexBlackList, const int & threshold) inline static
Filter a Read by its first index.
Parameters
r pointer to a Read object
indexBlackList a list of index to search against
threshold maximum different bases allowed for a succesful match
Returns
true if r's index is succesfully matched in the indexBlackList
Definition at line 81 of file filter.h.
{
             return Filter::match(indexBlackList, r->firstIndex(), threshold);
         }
References Read::firstIndex(), and match().
Referenced by filterByIndex().
filterByIndex() [2/2]
static bool Filter::filterByIndex (Read * r1, Read * r2, const std::vector< std::string > & indexBlackList, const int & threshold) inline static
Filter a pair of Read by their first index.
Parameters
r1 pointer to a Read object
r2 pointer to a Read object
indexBlackList a list of index to search against
threshold maximum different bases allowed for a succesful match
Returns
true if the first index of r1 or r2 succesfully matched in the indexBlackList
Definition at line 92 of file filter.h.
{
             return Filter::filterByIndex(r1, indexBlackList, threshold) || Filter::filterByIndex(r2, indexBlackList, threshold);
         }
References filterByIndex().
match()
bool Filter::match (const std::vector< std::string > & list, const std::string & target, int threshold) static
match a sequnce (target) against a series of sequences (list)
Parameters
list a vector of strings to be matched against
target a string to be tested whether it will match any string in list
threshold maximum character difference allowed for a successful match
Returns
true if any successful match occurs between target and string in list
Definition at line 185 of file filter.cpp.
{
     int tlen = target.length();
     int slen = 0;
     int diff = 0;
     for(int i = 0; i < list.size(); ++i){
         diff = 0;
         slen = list[i].length();
         for(int s = 0; s < slen && s < tlen; ++s){
             if(list[i][s] != target[s]){
                 ++diff;
                 if(diff > threshold){
                     break;
                 }
             }
         }
         if(diff <= threshold){
             return true;
         }
     }
     return false;
 }
Referenced by filterByIndex().
passFilter()
int Filter::passFilter (Read * r)
Test whether a Read pass filter.
Parameters
r pointer to a Read object
Returns
0 if passed
Definition at line 3 of file filter.cpp.
{
     if(r == NULL || r->length() == 0){
         return compar::FAIL_LENGTH;
     }
     int rlen = r->length();
     int lowQualNum = 0;
     int nBaseNum = 0;
     const char* seq = r->seq.seqStr.c_str();
     const char* qual = r->quality.c_str();
     if(this->lowQualThreshold > 0 || this->maxNBaseNum > 0 || this->minLen > 0 || this->maxLen > 0){
         for(int i = 0; i < rlen; ++i){
             if(seq[i] == 'N'){
                 ++nBaseNum;
             }
             if(qual[i] < this->lowQualThreshold){
                 ++lowQualNum;
             }
         }
     }
     if(this->lowQualThreshold > 0 && lowQualNum > this->maxLowQualNum){
         return compar::FAIL_QUALITY;
     }
     if(this->maxNBaseNum > 0 && nBaseNum > this->maxNBaseNum){
         return compar::FAIL_N_BASE;
     }
     if(this->minLen > 0 && rlen < this->minLen){
         return compar::FAIL_LENGTH;
     }
     if(this->maxLen > 0 && rlen > this->maxLen){
         return compar::FAIL_TOO_LONG;
     }
     if(this->minComplexity > 0 && !(this->passLowComplexityFliter(r))){
         return compar::FAIL_COMPLEXITY;
     }
     return compar::PASS_FILTER;
 }
References Read::length(), passLowComplexityFliter(), Read::quality, Read::seq, and Seq::seqStr.
passLowComplexityFliter()
bool Filter::passLowComplexityFliter (Read * r)
Test whether a Read pass low complexity filter.
Parameters
r pointer to a Read object
Returns
true if r is not low complexity
Definition at line 48 of file filter.cpp.
{
     int diff = 0;
     int rlen = r->length();
     if(rlen <= 1){
         return false;
     }
     const char* seq = r->seq.seqStr.c_str();
     for(int i = 0; i < rlen - 1; ++i){
         if(seq[i] != seq[i+1]){
             ++diff;
         }
     }
     return (double)diff/(rlen - 1) >= this->minComplexity;
 }
References Read::length(), Read::seq, and Seq::seqStr.
Referenced by passFilter().
trimAndCut()
Read * Filter::trimAndCut (Read * r, int forceFrontCut, int forceTailCut, QualCutOpt * opt) static
Trim and cut a Read by various methods.
Parameters
r pointer to a Read object
forceFrontCut force cut length from 5'end, will always happen
forceTailCut force cut length from 3'end, will always happen
opt vasious quality cut options, some may happen
Returns
a Read trim and cut properly
Definition at line 63 of file filter.cpp.
{
     // do not need quality cutting
     if(forceFrontCut == 0 && forceTailCut == 0 && !opt->cutFront && !opt->cutTail && !opt->cutRright){
         return r;
     }
     int rlen = r->length() - forceFrontCut - forceTailCut;
     if(rlen < 0){
         return NULL;
     }
     if(forceFrontCut == 0 && !opt->cutFront && !opt->cutTail && !opt->cutRright){
         r->resize(rlen);
         return r;
     }else if(!opt->cutFront && !opt->cutTail && !opt->cutRright){
         r->seq.seqStr = r->seq.seqStr.substr(forceFrontCut, rlen);
         r->quality = r->quality.substr(forceFrontCut, rlen);
         return r;
     }
     // need quality cutting
     int l = r->length();
     const char* qual = r->quality.c_str();
     const char* seq = r->seq.seqStr.c_str();
     // quality cutting forward by sliding window
     if(opt->cutFront){
         int w = opt->windowFront;
         int s = forceFrontCut;
         if(l - forceFrontCut - forceTailCut - w <= 0){
             return NULL;
         }
         int totalQual = 0;
         for(int i = 0; i < w - 1; ++i){
             totalQual += qual[s + i];
         }
         for(s = forceFrontCut; s + w < l - forceTailCut; ++s){
             totalQual += qual[s + w -1];
             if(s > forceFrontCut){
                 totalQual -= qual[s - 1];
             }
             if((double)totalQual/(double)w >= 33 + opt->minFrontQual){
                 break;
             }
         }
         if(s > 0){
             s = s + w -1;
         }
         // forceFrontCut is relocated one base before the last sliding window's last base and skip any N afterwards aswell
         while(s < l && seq[s] == 'N'){
             ++s;
         }
         forceFrontCut = s;
         rlen = l - forceFrontCut - forceTailCut;
     }
     // quality cutting from right by sliding window
     if(opt->cutRright){
         int w = opt->windowRight;
         int s = forceFrontCut;
         if(l - forceFrontCut - forceTailCut - w <= 0){
             return NULL;
         }
         int totalQual = 0;
         bool foundLowQualWindow = false;
         for(int i = 0; i < w - 1; ++i){
             totalQual += qual[s + i];
         }
         for(s = forceFrontCut; s + w < l - forceTailCut; ++s){
             totalQual += qual[s + w -1];
             if(s > forceFrontCut){
                 totalQual -= qual[s - 1];
             }
             if((double)totalQual/(double)w < 33 + opt->minRightQual){
                 foundLowQualWindow = true;
                 break;
             }
         }
         if(foundLowQualWindow){
             while(s < l - 1 && qual[s] >= 33 + opt->minRightQual){
                 ++s;
             }
             rlen = s - forceFrontCut;
         }
     }
     // quality cutting backward by sliding window
     if(!opt->cutRright && opt->cutTail){
         int w = opt->windowTail;
         if(l - forceFrontCut - forceTailCut - w <= 0){
             return NULL;
         }
         int totalQual = 0;
         int t = l - forceTailCut - 1;
         for(int i = 0; i < w - 1; ++i){
             totalQual += qual[t - i];
         }
         for(t = l - forceTailCut - 1; t - w >= forceFrontCut; --t){
             totalQual += qual[t - w + 1];
             if(t < l - forceTailCut - 1){
                 totalQual -= qual[t + 1];
             }
             if((double)totalQual/(double)w >= 33 + opt->minTailQual){
                 break;
             }
         }
         if(t < l - 1){
             t = t - w + 1;
         }
         while(t >= 0 && seq[t] == 'N'){
             --t;
         }
         rlen = t - forceFrontCut + 1;
     }
     if(rlen <= 0 || forceFrontCut >= l - 1){
         return NULL;
     }
     r->seq.seqStr = r->seq.seqStr.substr(forceFrontCut, rlen);
     r->quality = r->quality.substr(forceFrontCut, rlen);
     return r;
 }
References QualCutOpt::cutFront, QualCutOpt::cutRright, QualCutOpt::cutTail, Read::length(), QualCutOpt::minFrontQual, QualCutOpt::minRightQual, QualCutOpt::minTailQual, Read::quality, Read::resize(), Read::seq, Seq::seqStr, QualCutOpt::windowFront, QualCutOpt::windowRight, and QualCutOpt::windowTail.
The documentation for this class was generated from the following files:
filter.h
filter.cpp