UTIL: FilterResult Class Reference
FilterResult Class Reference
Class to store/calculate read filter results.
#include <filterresult.h>
Public Member Functions
FilterResult (FilterOpt *opt, bool paired=false)
Construct FilterResult object to store/calculate filter results.
~FilterResult ()
Destruct FilterResult object, free correctionMatrix.
void addAdapterTrimmed (const std::string &adapter, bool isR2=false)
Update FilterResult when a adapter trimming happened.
void addAdapterTrimmed (const std::string &adapter1, const std::string &adapter2)
Update FilterResult when adapter trimming happpened in pair end reads filtering.
void addCorrection (char from, char to)
add one case of base correction to FilterResult object, \nupdate the count in correctionMatrix,\n correctionMatrix[(from & 0x07) * 8 + (to & 0x07)] += 1
void addFilterResult (int result)
add filter status result to filter status result accumulation array
size_t * getCorrectionMatrix ()
get correction matrix(1x64 array)
size_t getCorrectionNum (char from, char to)
get base correction numbers in the pattern (from->to)
size_t * getFilterReadStats ()
get filterReadStats array(reads filter status accumulation array)
size_t getTotalCorrectedBases ()
get number of bases corrected
void incCorrectedReads (int count)
increase number of corrected reads
void reportAdaptersHtmlDetails (std::ofstream &ofs, std::map< std::string, size_t > &adapterCounts, size_t totalBases)
Report detailed trimmed adapter sequence and counts in html format.
void reportAdaptersHtmlSummary (std::ofstream &ofs, size_t totalBases)
Report summary trimmed adapter sequence and counts in html format.
void reportAdaptersJsonDetails (std::ofstream &ofs, std::map< std::string, size_t > &adapterCounts)
Report detailed trimmed adapter sequence and counts in json fomat.
void reportAdaptersJsonSummary (std::ofstream &ofs, const std::string &padding, const std::string &adapterSeq1, const std::string &adapterSeq2="")
Report summary trimmed adapter sequence and counts in json format.
void reportHtmlBasic (std::ofstream &ofs, size_t totalReads, size_t totalBases)
Report basic filter results to html file.
void reportJsonBasic (std::ofstream &ofs, const std::string &padding)
Report basic filter results to json file.
void summary (bool force=false)
summary the FilterResult object, in case recalculate some parameters again and again
Static Public Member Functions
static FilterResult * merge (std::vector< FilterResult * > &list)
merge list of FilterResult object into one(combine filter results of various parts of a fastq file)
Public Attributes
std::map< std::string, size_t > adapter1
read1 adapter trimmed count map
std::map< std::string, size_t > adapter2
read2 adapter trimmed count map
size_t correctedBases
number of bases got corrected
size_t correctedReads
number of reads got bases corrected
size_t * correctionMatrix
1x64 array to store various base to base correction accumulation numbers
size_t filterReadStats [compar::FILTER_RESULT_TYPES]
reads filter status accumulation array
FilterOpt * opt
pointer to FilterOpt object store various filter options
bool paired
pairend filter results if true, else single end results
bool summarized
whether a FilterResult has been summarized(i.e correctedBases calculated)
size_t trimmedAdapterBases
number of bases got trimmed when do adapter trimming
size_t trimmedAdapterReads
number of reads got adapter trimmed
Friends
std::ostream & operator<< (std::ostream &os, FilterResult *re)
Operator to output FilterResult to ostream.
Detailed Description
Class to store/calculate read filter results.
Definition at line 30 of file filterresult.h.
Constructor & Destructor Documentation
FilterResult()
FilterResult::FilterResult (FilterOpt * opt, bool paired = false)
Construct FilterResult object to store/calculate filter results.
Parameters
opt FilterOpt object to store various filter arguments
paired if true the FilterResult object store pairend filter results
Definition at line 3 of file filterresult.cpp.
{
     this->opt = opt;
     this->paired = paired;
     this->trimmedAdapterBases = 0;
     this->trimmedAdapterReads = 0;
     for(int i = 0; i < compar::FILTER_RESULT_TYPES; ++i){
         this->filterReadStats[i] = 0;
     }
     this->correctionMatrix = new size_t[64];
     std::memset(this->correctionMatrix, 0, sizeof(size_t) * 64);
     this->correctedReads = 0;
     this->summarized = false;
 }
References correctedReads, correctionMatrix, filterReadStats, opt, paired, summarized, trimmedAdapterBases, and trimmedAdapterReads.
Referenced by merge().
Member Function Documentation
addAdapterTrimmed() [1/2]
void FilterResult::addAdapterTrimmed (const std::string & adapter, bool isR2 = false)
Update FilterResult when a adapter trimming happened.
Parameters
adapter adapter sequence trimmed
isR2 if true the adapter was trimmed from read2
Definition at line 111 of file filterresult.cpp.
{
     if(adapter.empty()){
         return;
     }
     ++this->trimmedAdapterReads;
     this->trimmedAdapterBases += adapter.length();
     if(!isR2){
         if(this->adapter1.count(adapter) > 0){
             ++this->adapter1[adapter];
         }else{
             this->adapter1[adapter] = 1;
         }
     }else{
         if(this->adapter2.count(adapter) > 0){
             ++this->adapter2[adapter];
         }else{
             this->adapter2[adapter] = 1;
         }
     }
 }
References adapter1, adapter2, trimmedAdapterBases, and trimmedAdapterReads.
addAdapterTrimmed() [2/2]
void FilterResult::addAdapterTrimmed (const std::string & adapter1, const std::string & adapter2)
Update FilterResult when adapter trimming happpened in pair end reads filtering.
Parameters
adapter1 adapter sequence trimmed from read1
adapter2 adapter sequence trimmed from read2
Definition at line 132 of file filterresult.cpp.
{
     this->trimmedAdapterReads += 2;
     this->trimmedAdapterBases += adapterR1.length() + adapterR2.length();
     if(!adapterR1.empty()){
         if(this->adapter1.count(adapterR1) > 0){
             ++this->adapter1[adapterR1];
         }else{
             this->adapter1[adapterR1] = 1;
         }
     }
     if(!adapterR2.empty()){
         if(this->adapter2.count(adapterR2) > 0){
             ++this->adapter2[adapterR2];
         }else{
             this->adapter2[adapterR2] = 1;
         }
     }
 }
References adapter1, adapter2, trimmedAdapterBases, and trimmedAdapterReads.
addCorrection()
void FilterResult::addCorrection (char from, char to)
add one case of base correction to FilterResult object, \nupdate the count in correctionMatrix,\n correctionMatrix[(from & 0x07) * 8 + (to & 0x07)] += 1
Parameters
from source uncorrected base
to destination corrected base
Definition at line 95 of file filterresult.cpp.
{
     int f = from & 0x07;
     int t = from & 0x07;
     ++this->correctionMatrix[f * 8 +t];
 }
References correctionMatrix.
addFilterResult()
void FilterResult::addFilterResult (int result)
add filter status result to filter status result accumulation array
Parameters
result filter status
Definition at line 21 of file filterresult.cpp.
{
     if(result < compar::PASS_FILTER || result >= compar::FILTER_RESULT_TYPES){
         return;
     }
     if(this->paired){
         this->filterReadStats[result] += 2;
     }else{
         this->filterReadStats[result] += 1;
     }
 }
References filterReadStats, and paired.
getCorrectionMatrix()
size_t* FilterResult::getCorrectionMatrix () inline
get correction matrix(1x64 array)
Returns
pointer to correctionMatrix
Definition at line 137 of file filterresult.h.
{
             return this->correctionMatrix;
         }
References correctionMatrix.
Referenced by merge().
getCorrectionNum()
size_t FilterResult::getCorrectionNum (char from, char to)
get base correction numbers in the pattern (from->to)
Parameters
from source uncorrected base
to destination corrected base
Returns
base correction numbers in the pattern(from->to), just correctionMatrix[(from & 0x07) * 8 + (to & 0x07)]
Definition at line 105 of file filterresult.cpp.
{
     int f = from & 0x07;
     int t = to & 0x07;
     return this->correctionMatrix[f * 8 + t];
 }
References correctionMatrix.
getFilterReadStats()
size_t* FilterResult::getFilterReadStats () inline
get filterReadStats array(reads filter status accumulation array)
Returns
pointer to filterReadStats
Definition at line 56 of file filterresult.h.
{
             return this->filterReadStats;
         }
References filterReadStats.
Referenced by merge().
getTotalCorrectedBases()
size_t FilterResult::getTotalCorrectedBases ()
get number of bases corrected
Returns
number of based corrected
Definition at line 88 of file filterresult.cpp.
{
     if(!this->summarized){
         this->summary();
     }
     return this->correctedBases;
 }
References correctedBases, summarized, and summary().
Referenced by reportHtmlBasic(), and reportJsonBasic().
incCorrectedReads()
void FilterResult::incCorrectedReads (int count)
increase number of corrected reads
Parameters
count number of corrected reads to increase
Definition at line 101 of file filterresult.cpp.
{
     this->correctedReads += count;
 }
References correctedReads.
merge()
FilterResult * FilterResult::merge (std::vector< FilterResult * > & list) static
merge list of FilterResult object into one(combine filter results of various parts of a fastq file)
Parameters
list a vector of pointer to FilterResult object
Returns
pointer to the merged FilterResult object
Definition at line 32 of file filterresult.cpp.
{
     if(list.size() == 0){
         return NULL;
     }
     FilterResult* result = new FilterResult(list[0]->opt, list[0]->paired);
     size_t* target = result->getFilterReadStats();
     size_t* correction = result->getCorrectionMatrix();
     for(int i = 0; i < list.size(); ++i){
         // update filterReadStats
         size_t* curStats = list[i]->getFilterReadStats();
         for(int j = 0; j < compar::FILTER_RESULT_TYPES; ++j){
             target[j] += curStats[j];
         }
         // update correctionMatrix
         size_t* curCorr = list[i]->getCorrectionMatrix();
         for(int p = 0; p < 64; ++p){
             correction[p] += curCorr[p];
         }
         // update trimmedAdapterReads/bases
         result->trimmedAdapterReads += list[i]->trimmedAdapterReads;
         result->trimmedAdapterBases += list[i]->trimmedAdapterBases;
         // update read counting
         result->correctedReads += list[i]->correctedReads;
         // merge adapter stats
         for(auto& e: list[i]->adapter1){
             if(result->adapter1.count(e.first) > 0){
                 ++result->adapter1[e.first];
             }else{
                 result->adapter1[e.first] = 0;
             }
         }
         for(auto& e: list[i]->adapter2){
             if(result->adapter2.count(e.first) > 0){
                 ++result->adapter2[e.first];
             }else{
                 result->adapter2[e.first] = 0;
             }
         }
     }
     return result;
 }
References adapter1, adapter2, correctedReads, FilterResult(), getCorrectionMatrix(), getFilterReadStats(), opt, paired, trimmedAdapterBases, and trimmedAdapterReads.
reportAdaptersHtmlDetails()
void FilterResult::reportAdaptersHtmlDetails (std::ofstream & ofs, std::map< std::string, size_t > & adapterCounts, size_t totalBases)
Report detailed trimmed adapter sequence and counts in html format.
Parameters
ofs output file stream
adapterCounts adapter sequence counts map
totalBases totalBases total bases of fastq
Definition at line 252 of file filterresult.cpp.
{
     size_t totalAdapters = 0;
     size_t totalAdaptersBases = 0;
     for(auto& e: adapterCounts){
         totalAdapters += e.second;
         totalAdaptersBases += e.first.length();
     }
     double frac = (double)totalAdaptersBases / (double)totalBases;
     if(this->paired){
         frac *= 2.0;
     }
     if(frac < 0.01){
         ofs << "<div class='sub_section_tips'>The input has little adapter percentage (~" << std::to_string(frac * 100.0) << "%), probably it's trimmed before.</div>\n";
     }
     if(totalAdapters == 0){
         return;
     }
     ofs << "<table class='summary_table'>\n";
     ofs << "<tr><td class='adapter_col' style='font-size:14px;color:#ffffff;background:#556699'>" << "Sequence" << "</td><td class='col2' style='font-size:14px;color:#ffffff;background:#556699'>" << "Occurrences" << "</td    ></tr>\n";
     const double reportThreshold = 0.01;
     const double dTotalAdapters = (double)totalAdapters;
     size_t reported = 0;
     for(auto& e: adapterCounts){
         if(e.second / dTotalAdapters < reportThreshold){
             continue;
         }
         htmlutil::outputTableRow(ofs, e.first, e.second);
         reported += e.second;
     }
     size_t unreported = totalAdapters - reported;
     if(unreported > 0){
         std::string tag = "other adapter sequences";
         if(reported == 0){
             tag = "all adapter sequences";
         }
         htmlutil::outputTableRow(ofs, tag, unreported);
     }
     ofs << "</table>\n";
 }
References htmlutil::outputTableRow(), and paired.
Referenced by reportAdaptersHtmlSummary().
reportAdaptersHtmlSummary()
void FilterResult::reportAdaptersHtmlSummary (std::ofstream & ofs, size_t totalBases)
Report summary trimmed adapter sequence and counts in html format.
Parameters
ofs output file stream
totalBases totalBases total bases of fastq
Definition at line 313 of file filterresult.cpp.
{
     ofs << "<div class='subsection_title' onclick=showOrHide('read1_adapters')>Adapter or bad ligation of read1</div>\n";
     ofs << "<div id='read1_adapters'>\n";
     this->reportAdaptersHtmlDetails(ofs, this->adapter1, totalBases);
     ofs << "</div>\n";
     if(this->paired){
         ofs << "<div class='subsection_title' onclick=showOrHide('read2_adapters')>Adapter or bad ligation of read2</div>\n";
         ofs << "<div id='read2_adapters'>\n";
         this->reportAdaptersHtmlDetails(ofs, this->adapter2, totalBases);
         ofs << "</div>\n";
     }
 }
References adapter1, adapter2, paired, and reportAdaptersHtmlDetails().
reportAdaptersJsonDetails()
void FilterResult::reportAdaptersJsonDetails (std::ofstream & ofs, std::map< std::string, size_t > & adapterCounts)
Report detailed trimmed adapter sequence and counts in json fomat.
Parameters
ofs output file stream
adapterCounts adapter sequence counts map
Definition at line 218 of file filterresult.cpp.
{
     size_t totalAdapters = 0;
     for(auto& e: adapterCounts){
         totalAdapters += e.second;
     }
     if(totalAdapters == 0){
         return;
     }
     const double reportThreshold = 0.01;
     const double dTotalAdapters = (double)totalAdapters;
     bool firstItem = true;
     size_t reported = 0;
     for(auto& e: adapterCounts){
         if(e.second / dTotalAdapters < reportThreshold){
             continue;
         }
         if(!firstItem){
             ofs << ", ";
         }else{
             firstItem = false;
         }
         ofs << "\"" << e.first << "\":" << e.second;
         reported += e.second;
     }
     size_t unreported = totalAdapters - reported;
     if(unreported > 0){
         if(!firstItem){
             ofs << ", ";
         }else{
             ofs << "\"" << "others" << "\":" << unreported;
         }
     }
 }
Referenced by reportAdaptersJsonSummary().
reportAdaptersJsonSummary()
void FilterResult::reportAdaptersJsonSummary (std::ofstream & ofs, const std::string & padding, const std::string & adapterSeq1, const std::string & adapterSeq2 = "")
Report summary trimmed adapter sequence and counts in json format.
Parameters
ofs output file stream
padding padding before each json record
adapterSeq1 read1 adapter sequence
adapterSeq2 read2 adapter seqeunce
Definition at line 293 of file filterresult.cpp.
{
     ofs << "{\n";
     jsonutil::writeRecord(ofs, padding, "adapter_trimmed_reads", this->trimmedAdapterReads);
     jsonutil::writeRecord(ofs, padding, "adapter_trimmed_bases", this->trimmedAdapterBases);
     jsonutil::writeRecord(ofs, padding, "read1_adapter_sequence", adapterSeq1);
     if(this->paired){
         jsonutil::writeRecord(ofs, padding, "read2_adapter_sequence", adapterSeq2);
     }
     ofs << padding << "\t" << "\"read1_adapter_counts\": " << "{";
     this->reportAdaptersJsonDetails(ofs, this->adapter1);
     ofs << "}";
     if(this->paired){
         ofs << ",\n";
         ofs << padding << "\t" << "\"read2_adapter_counts\": " << "{";
         this->reportAdaptersJsonDetails(ofs, this->adapter2);
         ofs << "}\n";
     }
     ofs << padding << "}," << std::endl;
 }
References adapter1, adapter2, paired, reportAdaptersJsonDetails(), trimmedAdapterBases, trimmedAdapterReads, and jsonutil::writeRecord().
reportHtmlBasic()
void FilterResult::reportHtmlBasic (std::ofstream & ofs, size_t totalReads, size_t totalBases)
Report basic filter results to html file.
Parameters
ofs output file stream
totalReads total reads of fastq
totalBases total bases of fastq
Definition at line 198 of file filterresult.cpp.
{
     ofs << "<table class='summary_table'>\n";
     htmlutil::outputTableRow(ofs, "reads passed filters:", htmlutil::formatNumber(this->filterReadStats[compar::PASS_FILTER]) + " (" + std::to_string(this->filterReadStats[compar::PASS_FILTER] * 100.0 / totalBases) + "%)");
     htmlutil::outputTableRow(ofs, "low_quality_reads", htmlutil::formatNumber(this->filterReadStats[compar::FAIL_QUALITY]) + " (" + std::to_string(this->filterReadStats[compar::FAIL_QUALITY] * 100.0 / totalBases) + "%)");
     htmlutil::outputTableRow(ofs, "too_many_N_reads", htmlutil::formatNumber(this->filterReadStats[compar::FAIL_N_BASE]) + " (" + std::to_string(this->filterReadStats[compar::FAIL_N_BASE] * 100.0 / totalBases) + "%)");
     if(this->opt->baseCorrection){
         htmlutil::outputTableRow(ofs, "corrected_reads", htmlutil::formatNumber(this->correctedReads) + " (" + std::to_string(this->correctedReads * 100.0 / totalReads) + "%)");
         htmlutil::outputTableRow(ofs, "corrected_bases", htmlutil::formatNumber(this->getTotalCorrectedBases()) + " (" + std::to_string(this->getTotalCorrectedBases()) + " (" + std::to_string(this->getTotalCorrectedBases() * 100.0 / totalBases) + "%)");
     }
     if(this->opt->complexityFilter){
         htmlutil::outputTableRow(ofs, "low_complexity_reads", htmlutil::formatNumber(this->filterReadStats[compar::FAIL_COMPLEXITY]) + " (" + std::to_string(this->filterReadStats[compar::FAIL_COMPLEXITY] * 100.0 / totalReads) + "%)");
     }
     if(this->opt->filterShortRead){
         htmlutil::outputTableRow(ofs, "too_short_reads", htmlutil::formatNumber(this->filterReadStats[compar::FAIL_LENGTH]) + " (" + std::to_string(this->filterReadStats[compar::FAIL_LENGTH] * 100.0 / totalReads) + "%)");
     }
     if(this->opt->filterLongRead){
         htmlutil::outputTableRow(ofs, "too_long_reads", htmlutil::formatNumber(this->filterReadStats[compar::FAIL_TOO_LONG]) + " (" + std::to_string(this->filterReadStats[compar::FAIL_TOO_LONG] * 100.0 /totalReads) + "%)");
     }
 }
References FilterOpt::baseCorrection, FilterOpt::complexityFilter, correctedReads, FilterOpt::filterLongRead, filterReadStats, FilterOpt::filterShortRead, htmlutil::formatNumber(), getTotalCorrectedBases(), opt, and htmlutil::outputTableRow().
reportJsonBasic()
void FilterResult::reportJsonBasic (std::ofstream & ofs, const std::string & padding)
Report basic filter results to json file.
Parameters
ofs output file stream
padding padding before each json record
Definition at line 177 of file filterresult.cpp.
{
     ofs << "{\n";
     jsonutil::writeRecord(ofs, padding, "passed_filter_reads", this->filterReadStats[compar::PASS_FILTER]);
     jsonutil::writeRecord(ofs, padding, "low_quality_reads", this->filterReadStats[compar::FAIL_QUALITY]);
     jsonutil::writeRecord(ofs, padding, "too_many_N_reads", this->filterReadStats[compar::FAIL_N_BASE]);
     if(this->opt->baseCorrection){
         jsonutil::writeRecord(ofs, padding, "corrected_reads", this->correctedReads);
         jsonutil::writeRecord(ofs, padding, "corrected_bases", this->getTotalCorrectedBases());
     }
     if(this->opt->complexityFilter){
         jsonutil::writeRecord(ofs, padding, "low_complexity_reads", this->filterReadStats[compar::FAIL_COMPLEXITY]);
     }
     if(this->opt->filterShortRead){
         jsonutil::writeRecord(ofs, padding, "too_short_reads", this->filterReadStats[compar::FAIL_LENGTH]);
     }
     if(this->opt->filterLongRead){
         jsonutil::writeRecord(ofs, padding, "too_long_reads", this->filterReadStats[compar::FAIL_TOO_LONG]);
     }
     ofs << padding << "}," << std::endl;
 }
References FilterOpt::baseCorrection, FilterOpt::complexityFilter, correctedReads, FilterOpt::filterLongRead, filterReadStats, FilterOpt::filterShortRead, getTotalCorrectedBases(), opt, and jsonutil::writeRecord().
summary()
void FilterResult::summary (bool force = false)
summary the FilterResult object, in case recalculate some parameters again and again
Parameters
force if true, recalculate parameters
Definition at line 77 of file filterresult.cpp.
{
     if(this->summarized && !force){
         return;
     }
     this->correctedBases = 0;
     for(int p = 0; p < 64; ++p){
         this->correctedBases += this->correctionMatrix[p];
     }
     this->summarized = true;
 }
References correctedBases, correctionMatrix, and summarized.
Referenced by getTotalCorrectedBases().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, FilterResult * re) friend
Operator to output FilterResult to ostream.
Parameters
os reference of std::ostream object
re pointer of FilterResult object
Definition at line 152 of file filterresult.cpp.
{
     FilterOpt* fopt = re->opt;
     os << "reads passed filter: " << re->filterReadStats[compar::PASS_FILTER] << "\n";
     os << "reads failed due to low quality: " << re->filterReadStats[compar::FAIL_QUALITY] << "\n";
     os << "reads failed due to too many N: " << re->filterReadStats[compar::FAIL_N_BASE] << "\n";
     if(fopt->filterShortRead){
         os << "reads failed due to too short: " << re->filterReadStats[compar::FAIL_LENGTH] << "\n";
     }
     if(fopt->filterLongRead){
         os << "reads failed due to too long: " << re->filterReadStats[compar::FAIL_TOO_LONG] << "\n";
     }
     if(fopt->complexityFilter){
         os << "reads failed due to low complexity: " << re->filterReadStats[compar::FAIL_COMPLEXITY] << "\n";
     }
     if(fopt->trimAdapter){
         os << "reads with adapter trimmed: " << re->trimmedAdapterReads << "\n";
         os << "bases trimmed due to adapters: " << re->trimmedAdapterBases << "\n";
     }
     if(fopt->baseCorrection){
         os << "reads corrected by overlap analysis: " << re->correctedReads << "\n";
         os << "bases corrected by overlap analysis: " << re->getTotalCorrectedBases() << "\n";
     }
     return os;
 }
The documentation for this class was generated from the following files:
filterresult.h
filterresult.cpp