UTIL: FqReader Class Reference
FqReader Class Reference
Class to hold a fastq reader.
#include <fqreader.h>
Public Member Functions
FqReader (const std::string &filename, const bool &hasQuality=true, const bool &phread64=false)
Construct a FqReader with filename and hasQuality, phread64.
~FqReader ()
FqReader Destructor.
bool eof ()
Tell whether the FqReader has reach the endof file.
void getBytes (size_t &bytesRead, size_t &bytesTotal)
Get the number of Bytes read from(write to) the fastq file in the meantime, store it in bytesRead Get the total number of Bytes in the fastq file, store it in bytesTotal.
std::string getLine ()
get just one line from the buf, update the buf if needed
bool hasNoLineBreakAtEnd ()
Tell whether the fastq file has no '
' as a line break at the last line.
bool isZipped ()
Tell whether the fastq file is zipped or not.
Read * read ()
Try to get the next Read record from the current FqReader.
Static Public Member Functions
static bool isfq (const std::string &filename)
tell whether the file is a fastq format file
static bool isZippedFq (const std::string &filename)
tell whether the file is a zipped fastq file
Detailed Description
Class to hold a fastq reader.
Definition at line 13 of file fqreader.h.
Constructor & Destructor Documentation
FqReader()
FqReader::FqReader (const std::string & filename, const bool & hasQuality = true, const bool & phread64 = false)
Construct a FqReader with filename and hasQuality, phread64.
Parameters
filename Name of the fastq file
hasQuality The fastq has quality sequence if true
phread64 The fastq quality sequence is encoded as ASCII 64 if true
Definition at line 7 of file fqreader.cpp.
{
     this->fileName = fileName;
     this->gzipFile = NULL;
     this->pfile = NULL;
     this->stdinMode = false;
     this->phread64 = phread64;
     this->hasQuality = hasQuality;
     this->buf = new char[FQ_BUF_SIZE];
     this->bufDataLen = 0;
     this->bufUsedLen = 0;
     this->noLineBreakAtEnd = false;
     this->init();
 }
Member Function Documentation
eof()
bool FqReader::eof ()
Tell whether the FqReader has reach the endof file.
Returns
true if eof reached
Definition at line 158 of file fqreader.cpp.
                   {
     if(this->zipped){
         return ::gzeof(this->gzipFile);
     }else{
         return std::feof(this->pfile);
     }
 }
Referenced by read().
hasNoLineBreakAtEnd()
bool FqReader::hasNoLineBreakAtEnd ()
Tell whether the fastq file has no '
' as a line break at the last line.
Returns
true if the fastq file has no '
' as a line break at the last line
Definition at line 27 of file fqreader.cpp.
{
     return this->noLineBreakAtEnd;
 }
isfq()
bool FqReader::isfq (const std::string & filename) static
tell whether the file is a fastq format file
Parameters
filename file name
Returns
true if the file is a fastq file(with suffix ".fastq", ".fasta", ".fq" or ".fa)
Definition at line 225 of file fqreader.cpp.
{
     // just use the suffix of filename to determine its format
     if(util::ends_with(filename, ".fastq") || util::ends_with(filename, ".fq") ||
        util::ends_with(filename, ".fasta") || util::ends_with(filename, ".fa")){
         return true;
     }
     return false;
 }
References util::ends_with().
isZipped()
bool FqReader::isZipped ()
Tell whether the fastq file is zipped or not.
Returns
true if the fasq file is zipped
Definition at line 234 of file fqreader.cpp.
{
     return this->zipped;
 }
isZippedFq()
bool FqReader::isZippedFq (const std::string & filename) static
tell whether the file is a zipped fastq file
Parameters
filename file name
Returns
true if the file is a zipped fastq file(with suffix ".fastq.gz", ".fasta.gz", ".fq.gz" or ".fa.gz")
Definition at line 216 of file fqreader.cpp.
{
     // just use the suffix of filename to determine its format
     if(util::ends_with(filename, ".fastq.gz") || util::ends_with(filename, ".fq.gz") ||
        util::ends_with(filename, ".fasta.gz") || util::ends_with(filename, ".fa.gz")){
         return true;
     }
     return false;
 }
References util::ends_with().
read()
Read * FqReader::read ()
Try to get the next Read record from the current FqReader.
Returns
a pointer to object Read read from the current FqReader or NULL if failed during reading
Definition at line 166 of file fqreader.cpp.
                     {
     if(this->zipped && this->gzipFile == NULL){
         return NULL;
     }
     if(this->bufUsedLen >= this->bufDataLen && this->eof()){
         return NULL;
     }
     std::string name = this->getLine();
     while((name.empty() && !(this->bufUsedLen >= this->bufDataLen && this->eof())) || (!name.empty() && name[0] !='@')){
         name = this->getLine();
     }
     if(name.empty()){
         return NULL;
     }
     std::string sequence = this->getLine();
     std::string strand = this->getLine();
     // some fq has no quality, then construct the quality string with all 'K'
     if(!this->hasQuality){
         std::string quality = std::string(sequence.length(), 'K');
         return new Read(name, sequence, strand, quality, this->phread64);
     }else{
         std::string quality = this->getLine();
         if(quality.length() != sequence.length()){
             std::cerr << "Error: base sequnce and quality sequence have different length: \n";
             std::cerr << name << "\n";
             std::cerr << sequence << "\n";
             std::cerr << quality << "\n";
             std::cerr << strand << "\n";
             return NULL;
         }
         return new Read(name, sequence, strand, quality, this->phread64);
     }
     return NULL;
 }
References eof(), and getLine().
Referenced by Evaluator::computeOverRepSeq(), and FqReaderPair::read().
The documentation for this class was generated from the following files:
fqreader.h
fqreader.cpp