UTIL: Evaluator Class Reference
Evaluator Class Reference
class to hold various functions to evaluate sequence information
#include <evaluator.h>
Public Member Functions
Evaluator (const std::string &filename, const int &trlen)
Construct a evaluator with read1/2 filename.
~Evaluator ()
Destroy a evaluator.
void computeOverRepSeq (std::map< std::string, size_t > &hotSeqs)
Evaluate the fastq file over represented sequences based on at most this->readLen * 10000 bases count subsequences of length in {10, 20, 40, 100, min(150, this->readLen -2)} in each reads(total bases less than this->readLen * 10000) a subsequence will be considered as over represented if (length >= this->readLen - 1 && count >= 3) || (length >= 100 && count >= 5) || (length >= 40 && count >= 20) || (length >= 20 && count >= 100 || (length >= 10 && count >= 500) remove substrings in the map if the count of substring is less than 10 * count of the string contains it.
std::string getAdapter ()
get the estimated adapter sequence of this fastq file
int getReadLen ()
Get the estimated read length of the fastq file.
size_t getReadNum ()
get the estimated read number of this fastq file
bool isIlluminaAdapter ()
whether the adapter estimated is illumina know adapter
bool isTwoColorSystem ()
Test whether the read is sequenced from a TwoColorSystem machine.
Static Public Member Functions
static std::string int2seq (size_t val, int seqLen)
Convert a size_t value back into a string consists of ATCG with length seqLen.
static std::string matchKnownAdapter (const std::string &seq)
Match a sequence seq agains known illumina adapters stored in knownadapters.h seq length must be equal or greater than the matched adapter and match happens from index 0 between seq and adapter exactly to the end of adapter not any mismatch allowes.
static int seq2int (const std::string &seq, int pos, int seqLen, int lastVal=-1)
convert the substring started at pos to pos + seqLen - 1 of a string to int each 2 bits represents a nucleotide[A->00, T->01, C->10, G->11] from lowest bits to highest bits represent seq[pos + seqLen - 1] to seq[pos] if nucleotide other than ATCG occurs in this substring, -1 will return this sliding window algorithm will have a complexity of o(n)
Detailed Description
class to hold various functions to evaluate sequence information
Definition at line 17 of file evaluator.h.
Constructor & Destructor Documentation
Evaluator()
Evaluator::Evaluator (const std::string & filename, const int & trlen) inline
Construct a evaluator with read1/2 filename.
Parameters
trlen trim length from 3' end before evaluation
filename fastq filename
Definition at line 30 of file evaluator.h.
                                                                : trimLen(trlen), fqFile(filename){
             this->readLen = 0;
             this->readNum = 0;
             this->twoColorSystem = false;
             this->illuminaAdapter = false;
             this->adapter = "";
             this->evaluateReadLen();
             this->evaluateReadNum();
             this->evaluateTwoColorSystem();
         }
Member Function Documentation
computeOverRepSeq()
void Evaluator::computeOverRepSeq (std::map< std::string, size_t > & hotSeqs)
Evaluate the fastq file over represented sequences based on at most this->readLen * 10000 bases count subsequences of length in {10, 20, 40, 100, min(150, this->readLen -2)} in each reads(total bases less than this->readLen * 10000) a subsequence will be considered as over represented if (length >= this->readLen - 1 && count >= 3) || (length >= 100 && count >= 5) || (length >= 40 && count >= 20) || (length >= 20 && count >= 100 || (length >= 10 && count >= 500) remove substrings in the map if the count of substring is less than 10 * count of the string contains it.
Parameters
hotSeqs map to store over represented sequences
Definition at line 102 of file evaluator.cpp.
{
     FqReader fqr(this->fqFile);
     std::map<std::string, size_t> seqCounts;
     const size_t BASE_LIMIT = this->readLen * 10000;
     size_t records = 0;
     size_t bases = 0;
     Read* r = NULL;
     int rlen = 0;
     std::set<int> steps = {10, 20, 40, 100, std::min(150, this->readLen - 2)};
     std::string seq;
     size_t count;
     while(bases < BASE_LIMIT){
         r = fqr.read();
         if(!r){
             break;
         }
         rlen = r->length();
         bases += rlen;
         ++records;
         for(auto& step: steps){
             for(int i = 0; i < rlen - step; ++i){
                 seq = r->seq.seqStr.substr(i, step);
                 if(seqCounts.count(seq) > 0){
                     ++seqCounts[seq];
                 }else{
                     seqCounts[seq] = 1;
                 }
             }
         }
         delete r;
     }
     for(auto& e: seqCounts){
         seq = e.first;
         count = e.second;
         if((seq.length() >= this->readLen - 1 && count >= 3) ||
            (seq.length() >= 100 && count >= 5)        ||
            (seq.length() >= 40 && count >= 20)        ||
            (seq.length() >= 20 && count >= 100)       ||
            (seq.length() >= 10 && count >= 500)){
             hotSeqs[seq] = count;
         }
     }
     bool isSubstring = false;
     std::string seq2;
     size_t count2 = 0;
     std::map<std::string, size_t>::iterator iter, iter2;
     iter = hotSeqs.begin();
     while(iter != hotSeqs.end()){
         seq = iter->first;
         count = iter->second;
         isSubstring = false;
         for(iter2 = hotSeqs.begin(); iter2 != hotSeqs.end(); ++iter2){
             seq2 = iter2->first;
             count2 = iter2->second;
             if(seq != seq2 && seq2.find(seq) != std::string::npos && count / count2 < 10){
                 isSubstring = true;
                 break;
             }
         }
         if(isSubstring){
             hotSeqs.erase(iter++);
         }else{
             ++iter;
         }
     }
 }
References Read::length(), FqReader::read(), Read::seq, and Seq::seqStr.
Referenced by Stats::initOverRepSeq().
getAdapter()
std::string Evaluator::getAdapter () inline
get the estimated adapter sequence of this fastq file
Returns
the estimated adapter sequence of this fastq file
Definition at line 54 of file evaluator.h.
{
             this->evaluateAdapterSeq();
             return this->adapter;
         }
getReadLen()
int Evaluator::getReadLen () inline
Get the estimated read length of the fastq file.
Returns
the estimated read length of the fastq file
Definition at line 76 of file evaluator.h.
{
            return this->readLen;
         }
getReadNum()
size_t Evaluator::getReadNum () inline
get the estimated read number of this fastq file
Returns
the estimated read number of this fastq file
Definition at line 47 of file evaluator.h.
{
             return this->readNum;
         }
int2seq()
std::string Evaluator::int2seq (size_t val, int seqLen) static
Convert a size_t value back into a string consists of ATCG with length seqLen.
Parameters
val the encoded value of a nucleotide sequence
seqLen the encoded nucleotide sequence length
Returns
the nucleotide sequence of val encoded
Definition at line 52 of file evaluator.cpp.
{
     char bases[4] = {'A', 'T', 'C', 'G'};
     std::string ret(seqLen, 'N');
     int index = 0;
     while(index < seqLen){
         ret[seqLen - index -1] = bases[val & 0x03];
         val = (val >> 2);
         ++index;
     }
     return ret;
 }
Referenced by Stats::reportJson().
isIlluminaAdapter()
bool Evaluator::isIlluminaAdapter () inline
whether the adapter estimated is illumina know adapter
Returns
true if the adapter estimated is illumina know adapter
Definition at line 62 of file evaluator.h.
{
             return this->illuminaAdapter;
         }
isTwoColorSystem()
bool Evaluator::isTwoColorSystem () inline
Test whether the read is sequenced from a TwoColorSystem machine.
Returns
true if the read is sequenced from a TwoColorSystem machine
Definition at line 69 of file evaluator.h.
{
             return this->twoColorSystem;
         }
matchKnownAdapter()
std::string Evaluator::matchKnownAdapter (const std::string & seq) static
Match a sequence seq agains known illumina adapters stored in knownadapters.h seq length must be equal or greater than the matched adapter and match happens from index 0 between seq and adapter exactly to the end of adapter not any mismatch allowes.
Parameters
seq a nucleotide sequence(may generated from NeucleotideTree)
Returns
matched adapter sequence if successfuly or "" if failed
Definition at line 396 of file evaluator.cpp.
{
     std::map<std::string, std::string> knownAdapters = ::getKnownAdapter();
     std::map<std::string, std::string>::iterator iter;
     for(iter = knownAdapters.begin(); iter != knownAdapters.end(); ++iter) {
         std::string adapter = iter->first;
         std::string desc = iter->second;
         if(seq.length() < adapter.length()) {
             continue;
         }
         int diff = 0;
         for(int i=0; i < adapter.length() && i < seq.length(); ++i) {
             if(adapter[i] != seq[i])
                 ++diff;
         }
         if(diff == 0)
             return adapter;
     }
     return "";
 }
seq2int()
int Evaluator::seq2int (const std::string & seq, int pos, int seqLen, int lastVal = -1) static
convert the substring started at pos to pos + seqLen - 1 of a string to int each 2 bits represents a nucleotide[A->00, T->01, C->10, G->11] from lowest bits to highest bits represent seq[pos + seqLen - 1] to seq[pos] if nucleotide other than ATCG occurs in this substring, -1 will return this sliding window algorithm will have a complexity of o(n)
Parameters
seq the whole string
pos ini position of substring of seq
seqLen length of substring to be converted
lastVal the int representation of substring started at pos - 1 to pos + seqLen - 2 of string
Returns
int representation of the substring started at pos to pos + seqLen - 1 of string seq, may be -1
Definition at line 3 of file evaluator.cpp.
{
     int rlen = seq.length();
     if(lastVal >= 0){
         const int mask = (1 << (keylen * 2)) - 1;
         int key = (lastVal << 2) & mask;
         char base = seq[pos + keylen - 1];
         switch(base){
             case 'A':
                 key += 0;
                 break;
             case 'T':
                 key += 1;
                 break;
             case 'C':
                 key += 2;
                 break;
             case 'G':
                 key += 3;
                 break;
             default:
                 return -1;
         }
         return key;
     }else{
         int key = 0;
         for(int i = pos; i < pos + keylen; ++i){
             key = (key << 2);
             char base = seq[i];
             switch(base){
                 case 'A':
                     key += 0;
                     break;
                 case 'T':
                     key += 1;
                     break;
                 case 'C':
                     key += 2;
                     break;
                 case 'G':
                     key += 3;
                     break;
                 default:
                     return -1;
             }
         }
         return key;
     }
 }
Referenced by Stats::statRead().
The documentation for this class was generated from the following files:
evaluator.h
evaluator.cpp