UTIL: Stats Class Reference
Stats Class Reference
Class to do statistics of a fastq file.
#include <stats.h>
Public Member Functions
Stats (const int &estReadLen)
Construct a Stats object of fq with length estReadLen.
~Stats ()
Destroy a Stats object Free allocated mamory.
void allocateRes ()
Allocate resources for a Stats object.
size_t getBases ()
get total base number
int getCycles ()
get cycle number
size_t getGCNumber ()
get number of base G and C
int getMaxBaseQual ()
get maximum base quality
int getMaxReadLength ()
get maximum read length
int getMeanLength ()
get mean read length
int getMinBaseQual ()
get minimum base quality
int getMinReadLength ()
get minimum read length
size_t getQ20 ()
get number of bases with quality greater than 20
size_t getQ30 ()
get number of bases with quality greater than 30
size_t getReads ()
get total raeds number
void initOverRepSeq (Evaluator &fqEva)
Initialize overrepresentation analysis.
bool isLongRead ()
whether is long read fq
void reportHtml (std::ofstream &ofs, std::string filteringType, std::string readName)
Generate Html report.
void reportHtmlContents (std::ofstream &ofs, std::string filteringType, std::string readName)
Generate Content part of the Html report.
void reportHtmlKmer (std::ofstream &ofs, std::string filteringType, std::string readName)
Generate Kmer part of the Html report.
void reportHtmlORA (std::ofstream &ofs, std::string filteringType, std::string readName)
Generate Over representation analysis part of the Html report.
void reportHtmlQuality (std::ofstream &ofs, std::string filteringType, std::string readName)
Generate Quality part of the Html report.
void reportJson (std::ofstream &ofs, std::string padding)
Generate json report.
void setKmerLen (const int kLen)
Set Kmer length to calculate.
void setOverRepSampleFreq (int readFreq)
Set over representation analysis sampling frequence.
void statRead (Read *r)
do statistics of one read
void summarize (bool forced=false)
Summary statistic items, get this->bases, this->cycles, this->q20Bases, this->q30Bases, this->q20Total, this->q30Total, this->qualityCurves["mean"], this->qualityCurves["A/T/C/G/N"], this->contentCurves["A/T/C/G/N"], this->contentCurves["GC"] this->kmerMin, this->kmerMax, after summary, this->summarize will be set to true.
Static Public Member Functions
template<typename T >
static std::string list2string (T *list, int size)
convert an array of value type T to a string seperated by ","
template<typename T >
static std::string list2string (T *list, int size, size_t *coords)
convert an array of T values to a string seperated by ","
static Stats * merge (std::vector< Stats * > &list)
merge a list of Stats objects into one
Friends
std::ostream & operator<< (std::ostream &os, const Stats &s)
output Stats object to std::ostream
Detailed Description
Class to do statistics of a fastq file.
Definition at line 17 of file stats.h.
Member Function Documentation
getBases()
size_t Stats::getBases ()
get total base number
Returns
total base number
Definition at line 319 of file stats.cpp.
                       {
     if(!this->summarized){
         this->summarize();
     }
     return this->bases;
 }
References summarize().
getCycles()
int Stats::getCycles ()
get cycle number
Returns
cycle number
Definition at line 305 of file stats.cpp.
                     {
     if(!this->summarized){
         this->summarize();
     }
     return this->cycles;
 }
References summarize().
Referenced by getMaxReadLength(), and merge().
getGCNumber()
size_t Stats::getGCNumber ()
get number of base G and C
Returns
number of base G and C
Definition at line 340 of file stats.cpp.
{
     if(!this->summarized){
         this->summarize();
     }
     return this->baseContents['G' & 0x07] + this->baseContents['C' & 0x07];
 }
References summarize().
getMaxBaseQual()
int Stats::getMaxBaseQual ()
get maximum base quality
Returns
maximum base quality
Definition at line 298 of file stats.cpp.
{
     if(!this->summarized){
         this->summarize();
     }
     return this->maxQual;
 }
References summarize().
getMaxReadLength()
int Stats::getMaxReadLength ()
get maximum read length
Returns
maximum read length
Definition at line 287 of file stats.cpp.
{
     return this->getCycles();
 }
References getCycles().
Referenced by merge().
getMeanLength()
int Stats::getMeanLength ()
get mean read length
Returns
mean read length
Definition at line 213 of file stats.cpp.
{
     if(this->reads == 0){
         return 0;
     }
     return this->lengthSum/this->reads;
 }
getMinBaseQual()
int Stats::getMinBaseQual ()
get minimum base quality
Returns
minimum base quality
Definition at line 291 of file stats.cpp.
{
     if(!this->summarized){
         this->summarize();
     }
     return this->minQual;
 }
References summarize().
getMinReadLength()
int Stats::getMinReadLength ()
get minimum read length
Returns
minimum read length
Definition at line 280 of file stats.cpp.
{
     if(!this->summarized){
         this->summarize();
     }
     return this->minReadLen;
 }
References summarize().
getQ20()
size_t Stats::getQ20 ()
get number of bases with quality greater than 20
Returns
number of bases with quality greater than 20
Definition at line 326 of file stats.cpp.
                     {
     if(!this->summarized){
         this->summarize();
     }
     return this->q20Total;
 }
References summarize().
getQ30()
size_t Stats::getQ30 ()
get number of bases with quality greater than 30
Returns
number of bases with quality greater than 30
Definition at line 333 of file stats.cpp.
                     {
     if(!this->summarized){
         this->summarize();
     }
     return this->q30Total;
 }
References summarize().
getReads()
size_t Stats::getReads ()
get total raeds number
Returns
total read number
Definition at line 312 of file stats.cpp.
                       {
     if(!this->summarized){
         this->summarize();
     }
     return this->reads;
 }
References summarize().
initOverRepSeq()
void Stats::initOverRepSeq (Evaluator & fqEva)
Initialize overrepresentation analysis.
Parameters
fqEva Evaluator object used to compute representatin sequences
Definition at line 886 of file stats.cpp.
{
     fqEva.computeOverRepSeq(this->overRepSeq);
     for(auto& e : this->overRepSeq){
         e.second = 0;
         this->overRepSeqDist[e.first] = new size_t[this->evaluatedSeqLen];
         std::memset(this->overRepSeqDist[e.first], 0, sizeof(size_t) * this->evaluatedSeqLen);
     }
 }
References Evaluator::computeOverRepSeq().
isLongRead()
bool Stats::isLongRead ()
whether is long read fq
Returns
true if this->cycles > 300
Definition at line 496 of file stats.cpp.
                       {
     return this->cycles > 300;
 }
Referenced by reportHtmlContents(), and reportHtmlQuality().
list2string() [1/2]
template<typename T > std::string Stats::list2string (T * list, int size) static
convert an array of value type T to a string seperated by ","
Parameters
list pointer to a T value array
size the length of the T value array
Definition at line 442 of file stats.cpp.
{
     std::stringstream ss;
     for(int i = 0; i < size; ++i){
         ss << list[i];
         if(i < size - 1){
             ss << ",";
         }
     }
     return ss.str();
 }
Referenced by reportHtmlContents(), and reportHtmlQuality().
list2string() [2/2]
template<typename T > std::string Stats::list2string (T * list, int size, size_t * coords) static
convert an array of T values to a string seperated by ","
Parameters
list pointer to a T value array
size the length of the T value array
coords coordinates to define the ith value output ith value output equals average of(list[coords[i-1]] ... list[coords[i]])
Definition at line 454 of file stats.cpp.
{
     std::stringstream ss;
     long start = 0;
     long end = 0;
     T total = 0;
     for(int i = 0; i < size; ++i){
         if(i > 0){
             start = coords[i - 1];
         }
         end = coords[i];
         total = 0;
         for(int j = start; j < end; ++j){
             total += list[j];
         }
         if(end == start){
             ss << "0";
         }else{
             ss << total /(end - start);
         }
         if(i < size - 1){
             ss << ",";
         }
     }
     return ss.str();
 }
merge()
Stats * Stats::merge (std::vector< Stats * > & list) static
merge a list of Stats objects into one
Parameters
list a list of Stats objects
Returns
a merged Stats object
Definition at line 827 of file stats.cpp.
{
     if(list.size() == 0){
         return NULL;
     }
     int c = 0;
     int kl = 0;
     int smp = 0;
     int rdl = 0;
     for(int i = 0; i < list.size(); ++i){
         list[i]->summarize();
         c = std::max(c, list[i]->getCycles());
         kl = std::max(kl, list[i]->kmerLen);
         smp = std::max(smp, list[i]->overRepSampleFreq);
         rdl = std::max(rdl, list[i]->getMaxReadLength());
     }
     Stats* s = new Stats(rdl);
     s->setKmerLen(kl);
     s->setOverRepSampleFreq(smp);
     s->allocateRes();
     for(int i = 0; i < list.size(); ++i){
         int curCycles = list[i]->getCycles();
         s->reads += list[i]->reads;
         s->lengthSum += list[i]->lengthSum;
         for(int j = 0; j < 8; ++j){
             for(int k = 0; k < c && k < curCycles; ++k){
                 s->cycleQ30Bases[j][k] += list[i]->cycleQ30Bases[j][k];
                 s->cycleQ20Bases[j][k] += list[i]->cycleQ20Bases[j][k];
                 s->cycleBaseContents[j][k] += list[i]->cycleBaseContents[j][k];
                 s->cycleBaseQual[j][k] += list[i]->cycleBaseQual[j][k];
             }
         }
         for(int j = 0; j < c && j < curCycles; ++j){
             s->cycleTotalBase[j] += list[i]->cycleTotalBase[j];
             s->cycleTotalQual[j] += list[i]->cycleTotalQual[j];
         }
         if(s->kmerLen){
             for(int j = 0; j < s->kmerBufLen; ++j){
                 s->kmer[j] += list[i]->kmer[j];
             }
         }
         if(s->overRepSampleFreq){
             for(auto& e: s->overRepSeq){
                 s->overRepSeq[e.first] += list[i]->overRepSeq[e.first];
                 for(int j = 0; j < s->evaluatedSeqLen; ++j){
                     s->overRepSeqDist[e.first][j] += list[i]->overRepSeqDist[e.first][j];
                 }
             }
         }
     }
     s->summarize();
     return s;
 }
References allocateRes(), getCycles(), getMaxReadLength(), setKmerLen(), setOverRepSampleFreq(), Stats(), and summarize().
reportHtml()
void Stats::reportHtml (std::ofstream & ofs, std::string filteringType, std::string readName)
Generate Html report.
Parameters
ofs std::ofstream to output report
filteringType filtering type of report
readName library name
Definition at line 500 of file stats.cpp.
{
     this->reportHtmlQuality(ofs, filteringType, readName);
     this->reportHtmlContents(ofs, filteringType, readName);
     if(this->kmerLen){
         this->reportHtmlKmer(ofs, filteringType, readName);
     }
     if(this->overRepSampleFreq){
         this->reportHtmlORA(ofs, filteringType, readName);
     }
 }
References reportHtmlContents(), reportHtmlKmer(), reportHtmlORA(), and reportHtmlQuality().
reportHtmlContents()
void Stats::reportHtmlContents (std::ofstream & ofs, std::string filteringType, std::string readName)
Generate Content part of the Html report.
Parameters
ofs std::ofstream to output report
filteringType filtering type of report
readName library name
Definition at line 736 of file stats.cpp.
{
     // content
     std::string subsection = filteringType + ": " + readName + ": base contents";
     std::string divName = util::replace(subsection, " ", "_");
     divName = util::replace(divName, ":", "_");
     std::string title = "";
     ofs << "<div class='subsection_title'><a title='click to hide/show' onclick=showOrHide('" << divName << "')>" + subsection + "</a></div>\n";
     ofs << "<div id='" + divName + "'>\n";
     ofs << "<div class='sub_section_tips'>Value of each position will be shown on mouse over.</div>\n";
     ofs << "<div class='figure' id='plot_" + divName + "'></div>\n";
     ofs << "</div>\n";
     std::string alphabets[6] = {"A", "T", "C", "G", "N", "GC"};
     std::string colors[6] = {"rgba(128,128,0,1.0)", "rgba(128,0,128,1.0)", "rgba(0,255,0,1.0)", "rgba(0,0,255,1.0)", "rgba(255, 0, 0, 1.0)", "rgba(20,20,20,1.0)"};
     ofs << "\n<script type=\"text/javascript\">" << std::endl;
     std::string json_str = "var data=[";
     size_t *x = new size_t[this->cycles];
     int total = 0;
     if(!this->isLongRead()) {
         for(int i=0; i<this->cycles; i++){
             x[total] = i+1;
             total++;
         }
     } else {
         const int fullSampling = 40;
         for(int i=0; i<fullSampling && i<this->cycles; i++){
             x[total] = i+1;
              total++;
         }
         // down sampling if it's too long
         if(this->cycles > fullSampling) {
             double pos = fullSampling;
             while(true){
                 pos *= 1.05;
                 if(pos >= this->cycles)
                     break;
                 x[total] = (int)pos;
                 total++;
             }
             // make sure lsat one is contained
             if(x[total-1] != this->cycles){
                 x[total] = this->cycles;
                 total++;
              }
         }
     }
     // four bases
     for (int b = 0; b<6; b++) {
         std::string base = alphabets[b];
         long count = 0;
         if(base.size()==1) {
             char b = base[0] & 0x07;
             count = this->baseContents[b];
         } else {
             count = this->baseContents['G' & 0x07] + this->baseContents['C' & 0x07] ;
         }
         std::string percentage = std::to_string((double)count * 100.0 / this->bases);
         if(percentage.length()>5)
             percentage = percentage.substr(0,5);
         std::string name = base + "(" + percentage + "%)";
         json_str += "{";
         json_str += "x:[" + list2string(x, total) + "],";
         json_str += "y:[" + list2string(this->contentCurves[base], total, x) + "],";
         json_str += "name: '" + name + "',";
         json_str += "mode:'lines',";
         json_str += "line:{color:'" + colors[b] + "', width:1}\n";
         json_str += "},";
     }
     json_str += "];\n";
     json_str += "var layout={title:'" + title + "', xaxis:{title:'position'";
     json_str += ", tickmode: 'auto', nticks: '";
     json_str += std::to_string(this->cycles/5) + "'";
     // use log plot if it's too long
     if(this->isLongRead()) {
         json_str += ",type:'log'";
     }
     json_str += "}, yaxis:{title:'base content ratios'";
     json_str += ", tickmode: 'auto', nticks: '20', range: ['0.0', '1.0']";
     json_str += "}};\n";
     json_str += "Plotly.newPlot('plot_" + divName + "', data, layout);\n";
     ofs << json_str;
     ofs << "</script>" << std::endl;
     delete[] x;
 }
References isLongRead(), list2string(), and util::replace().
Referenced by reportHtml().
reportHtmlKmer()
void Stats::reportHtmlKmer (std::ofstream & ofs, std::string filteringType, std::string readName)
Generate Kmer part of the Html report.
Parameters
ofs std::ofstream to output report
filteringType filtering type of report
readName library name
Definition at line 592 of file stats.cpp.
{
     // KMER
     std::string subsection = filteringType + ": " + readName + ": KMER counting";
     std::string divName = util::replace(subsection, " ", "_");
     divName = util::replace(divName, ":", "_");
     std::string title = "";
     ofs << "<div class='subsection_title'><a title='click to hide/show' onclick=showOrHide('" << divName << "')>" + subsection + "</a></div>\n";
     ofs << "<div  id='" << divName << "'>\n";
     ofs << "<div class='sub_section_tips'>Darker background means larger counts. The count will be shown on mouse over.</div>\n";
     ofs << "<table class='kmer_table' style='width:680px;'>\n";
     ofs << "<tr>";
     ofs << "<td></td>";
     // the heading row
     for(int h = 0; h < (1 << this->kmerLen); ++h){
         ofs << "<td style='color:#333333'>" << std::to_string(h + 1) << "</td>";
     }
     ofs << "</tr>\n";
     // content
     size_t n = 0;
     for(size_t i = 0; i < (1 << this->kmerLen); ++i){
         ofs << "<tr>";
         ofs << "<td style='color:#333333'>" << std::to_string(i + 1) << "</td>";
         for(int j = 0; j < (1 << this->kmerLen); ++j){
             ofs << this->makeKmerTD(n++);
         }
         ofs << "</tr>\n";
     }
     ofs << "</table>\n";
     ofs << "</div>\n";
 }
References util::replace().
Referenced by reportHtml().
reportHtmlORA()
void Stats::reportHtmlORA (std::ofstream & ofs, std::string filteringType, std::string readName)
Generate Over representation analysis part of the Html report.
Parameters
ofs std::ofstream to output report
filteringType filtering type of report
readName library name
Definition at line 511 of file stats.cpp.
{
     double dBases = this->bases;
     int displayed = 0;
     std::string subSection = filteringType + ": " + readName + ": overrepresented sequences";
     std::string divName = util::replace(subSection, " ", "_");
     divName = util::replace(divName, ":", "_");
     std::string title = "";
     ofs << "<div class='subsection_title'><a title='click to hide/show' onclick=showOrHide('";
     ofs << divName << "')>" << subSection << "</a></div>\n";
     ofs << "<div id='" << divName << "'>\n";
     ofs << "<div class='sub_section_tips'>Sampling rate: 1 / " << this->overRepSampleFreq << "</div>\n";
     ofs << "<table class='summary_table'>\n";
     ofs << "<tr style='font-weight:bold;'><td>overrepresented sequence</td><td>count (% of bases)</td><td>distribution: cycle 1 ~ cycle " << this->evaluatedSeqLen << "</td></tr>"<<std::endl;
     int found = 0;
     for(auto& e: this->overRepSeq){
         std::string seq = e.first;
         size_t count = e.second;
         if(!this->overRepPassed(seq, count))
             continue;
         found++;
         double percent = (100.0 * count * seq.length() * this->overRepSampleFreq)/dBases;
         ofs << "<tr>";
         ofs << "<td width='400' style='word-break:break-all;font-size:8px;'>" << seq << "</td>";
         ofs << "<td width='200'>" << count << " (" << std::to_string(percent) <<"%)</td>";
         ofs << "<td width='250'><canvas id='" << divName << "_" << seq << "' width='240' height='20'></td>";
         ofs << "</tr>" << std::endl;
     }
     if(found == 0)
         ofs << "<tr><td style='text-align:center' colspan='3'>not found</td></tr>" << std::endl;
     ofs << "</table>\n";
     ofs << "</div>\n";
     // output the JS
     ofs << "<script language='javascript'>" << std::endl;
     ofs << "var seqlen = " << this->evaluatedSeqLen << ";" << std::endl;
     ofs << "var orp_dist = {" << std::endl;
     bool first = true;
     for(auto& e: this->overRepSeq){
         std::string seq = e.first;
         size_t count = e.second;
         if(!overRepPassed(seq, count))
             continue;
         if(!first) {
             ofs << "," << std::endl;
         } else
             first = false;
         ofs << "\t\"" << divName << "_" << seq << "\":[";
         for(int i=0; i< this->evaluatedSeqLen; ++i){
             if(i !=0 )
                 ofs << ",";
             ofs << this->overRepSeqDist[seq][i];
         }
         ofs << "]";
     }
         ofs << "\n};" << std::endl;
     ofs << "for (seq in orp_dist) {"<< std::endl;
     ofs << "    var cvs = document.getElementById(seq);"<< std::endl;
     ofs << "    var ctx = cvs.getContext('2d'); "<< std::endl;
     ofs << "    var data = orp_dist[seq];"<< std::endl;
     ofs << "    var w = 240;"<< std::endl;
     ofs << "    var h = 20;"<< std::endl;
     ofs << "    ctx.fillStyle='#cccccc';"<< std::endl;
     ofs << "    ctx.fillRect(0, 0, w, h);"<< std::endl;
     ofs << "    ctx.fillStyle='#0000FF';"<< std::endl;
     ofs << "    var maxVal = 0;"<< std::endl;
     ofs << "    for(d=0; d<seqlen; d++) {"<< std::endl;
     ofs << "        if(data[d]>maxVal) maxVal = data[d];"<< std::endl;
     ofs << "    }"<< std::endl;
     ofs << "    var step = (seqlen-1) /  (w-1);"<< std::endl;
     ofs << "    for(x=0; x<w; x++){"<< std::endl;
     ofs << "        var target = step * x;"<< std::endl;
     ofs << "        var val = data[Math.floor(target)];"<< std::endl;
     ofs << "        var y = Math.floor((val / maxVal) * h);"<< std::endl;
     ofs << "        ctx.fillRect(x,h-1, 1, -y);"<< std::endl;
     ofs << "    }"<< std::endl;
     ofs << "}"<< std::endl;
     ofs << "</script>"<< std::endl;
 }
References util::replace().
Referenced by reportHtml().
reportHtmlQuality()
void Stats::reportHtmlQuality (std::ofstream & ofs, std::string filteringType, std::string readName)
Generate Quality part of the Html report.
Parameters
ofs std::ofstream to output report
filteringType filtering type of report
readName library name
Definition at line 658 of file stats.cpp.
{
     // quality
     std::string subsection = filteringType + ": " + readName + ": quality";
     std::string divName = util::replace(subsection, " ", "_");
     divName = util::replace(divName, ":", "_");
     std::string title = "";
     ofs << "<script type=\"text/javascript\" src=\"./plotly.js\"></script>\n";
     ofs << "<div class='subsection_title'><a title='click to hide/show' onclick=showOrHide('" << divName << "')>" + subsection + "</a></div>\n";
     ofs << "<div id='" + divName + "'>\n";
     ofs << "<div class='sub_section_tips'>Value of each position will be shown on mouse over.</div>\n";
     ofs << "<div class='figure' id='plot_" + divName + "'></div>\n";
     ofs << "</div>\n";
     std::string alphabets[5] = {"A", "T", "C", "G", "mean"};
     std::string colors[5] = {"rgba(128,128,0,1.0)", "rgba(128,0,128,1.0)", "rgba(0,255,0,1.0)", "rgba(0,0,255,1.0)", "rgba(20,20,20,1.0)"};
     ofs << "\n<script type=\"text/javascript\">" << std::endl;
     std::string json_str = "var data=[";
     size_t *x = new size_t[this->cycles];
     int total = 0;
     if(!this->isLongRead()) {
         for(int i = 0; i < this->cycles; ++i){
             x[total] = i + 1;
             total++;
         }
     } else {
         const int fullSampling = 40;
         for(int i=0; i < fullSampling && i < this->cycles; i++){
             x[total] = i + 1;
             total++;
         }
         // down sampling if it's too long
         if(this->cycles > fullSampling) {
             double pos = fullSampling;
             while(true){
                 pos *= 1.05;
                 if(pos >= this->cycles)
                     break;
                 x[total] = (int)pos;
                 total++;
             }
             // make sure lsat one is contained
             if(x[total-1] != this->cycles){
                 x[total] = this->cycles;
                 total++;
             }
         }
     }
     // four bases
     for (int b = 0; b<5; b++) {
         std::string base = alphabets[b];
         json_str += "{";
         json_str += "x:[" + this->list2string(x, total) + "],";
         json_str += "y:[" + this->list2string(this->qualityCurves[base], total, x) + "],";
         json_str += "name: '" + base + "',";
         json_str += "mode:'lines',";
         json_str += "line:{color:'" + colors[b] + "', width:1}\n";
         json_str += "},";
     }
     json_str += "];\n";
     json_str += "var layout={title:'" + title + "', xaxis:{title:'position'";
     json_str += ", tickmode: 'auto', nticks: '";
     json_str += std::to_string(this->cycles/5) + "'";
     // use log plot if it's too long
     if(this->isLongRead()) {
         json_str += ",type:'log'";
     }
     json_str += "},";
     json_str += "yaxis:{title:'quality', tickmode: 'auto', nticks: '20'";
     json_str += "}};\n";
     json_str += "Plotly.newPlot('plot_" + divName + "', data, layout);\n";
     ofs << json_str;
     ofs << "</script>" << std::endl;
     delete[] x;
 }
References isLongRead(), list2string(), and util::replace().
Referenced by reportHtml().
reportJson()
void Stats::reportJson (std::ofstream & ofs, std::string padding)
Generate json report.
Parameters
ofs std::ofstream to output report
padding padding in front of each line
Definition at line 355 of file stats.cpp.
{
     // braces
     ofs << "{\n";
     // basic qc info
     ofs << padding << "\t\"total_reads\": " << this->reads << ",\n";
     ofs << padding << "\t\"total_bases\": " << this->bases << ",\n";
     ofs << padding << "\t\"q20_bases\": " << this->q20Total << ",\n";
     ofs << padding << "\t\"q30_bases\": " << this->q30Total << ",\n";
     ofs << padding << "\t\"total_cycles\": " << this->cycles << ",\n";
     // quality curves
     std::string qualNames[5] = {"A", "T", "C", "G", "mean"};
     ofs << padding << "\t\"quality_curves\": {\n";
     for(int i = 0; i < 5; ++i){
         std::string name = qualNames[i];
         double* curve = this->qualityCurves[name];
         ofs << padding << "\t\t\"" << name << "\":[";
         for(int c = 0; c < this->cycles; ++c){
             ofs << curve[c];
             if(c != this->cycles - 1){
                 ofs << ",";
             }
         }
         ofs << "]";
         if(i != 4){
             ofs << ",";
         }
         ofs << "\n";
     }
     ofs << padding << "\t},\n";
     //content curves
     std::string contentNames[6] = {"A", "T", "C", "G", "N", "GC"};
     ofs << padding << "\t\"content_curves\":{\n";
     for(int i = 0; i < 6; ++i){
         std::string name = contentNames[i];
         double* curve = this->contentCurves[name];
         ofs << padding << "\t\t\"" << name << "\":[";
         for(int c = 0; c < this->cycles; ++c){
             ofs << curve[c];
             if(c != this->cycles - 1){
                 ofs << ",";
             }
         }
         ofs << "]";
         if(i != 5){
             ofs << ",";
         }
         ofs << "\n";
     }
     ofs << padding << "\t}";
     //KMER counting(optional)
     std::string maxKmerInt = std::to_string(this->kmerMax);
     int maxWidth = maxKmerInt.length();
     if(this->kmerLen){
         ofs << ",\n";
         ofs << padding << "\t" << "\"kmer_count\": {\n";
         for(size_t i = 0; i < this->kmerBufLen; ++i){
             std::string seq = Evaluator::int2seq(i, this->kmerLen);
             if(i % (1 << this->kmerLen)){
                 ofs << "\"" << seq << "\":" << std::left << std::setw(maxWidth + 1) << std::to_string(this->kmer[i]) +",";
             }else{
                 ofs << "\n" << padding << "\t\t\"" << seq << "\":" << std::left << std::setw(maxWidth + 1) << std::to_string(this->kmer[i]) + ",";
             }
         }
         ofs << padding << "\t}";
     }
     // over represented seqs(optional)
     if(this->overRepSampleFreq){
         ofs << ",\n";
         ofs << padding << "\t\"overrepresented_sequences\": {\n";
         bool first = true;
         for(auto& e : this->overRepSeq){
             if(!this->overRepPassed(e.first, e.second)){
                 continue;
             }
             if(!first){
                 ofs << ",\n";
             }else{
                 first = false;
             }
             ofs << padding << "\t\t\"" << e.first << "\":" << e.second;
         }
         ofs << padding << "\t}\n";
     }
     ofs << padding << "\n}\n";
 }
References Evaluator::int2seq().
setKmerLen()
void Stats::setKmerLen (const int kLen) inline
Set Kmer length to calculate.
Parameters
kLen Kmer length, if kLen = 0, Kmer statistics will not be done
Definition at line 61 of file stats.h.
{
             this->kmerLen = kLen;
             this->kmerBufLen = (1 << (this->kmerLen * 2));
         }
Referenced by merge().
setOverRepSampleFreq()
void Stats::setOverRepSampleFreq (int readFreq) inline
Set over representation analysis sampling frequence.
Parameters
readFreq if readFreq = 0, over representation analysis will not be done
Definition at line 69 of file stats.h.
{
             this->overRepSampleFreq = readFreq;
         }
Referenced by merge().
statRead()
void Stats::statRead (Read * r)
do statistics of one read
Parameters
r pointer to object Read
Definition at line 220 of file stats.cpp.
{
     int len = r->length();
     this->lengthSum += len;
     if(this->bufLen < len){
         this->extendBuffer(std::max(len + 100, (int)(len * 1.5)));
     }
     const std::string seqStr = r->seq.seqStr;
     const std::string qualStr = r->quality;
     int kmerVal = -1;
     for(int i = 0; i < len; ++i){
         char base = seqStr[i];
         char qual = qualStr[i];
         char bIndex = base & 0x07;
         const char q20 = '5';
         const char q30 = '?';
         this->minQual = std::min(qual - 33, this->minQual);
         this->maxQual = std::max(qual - 33, this->maxQual);
         if(qual > q30){
             ++this->cycleQ20Bases[bIndex][i];
             ++this->cycleQ30Bases[bIndex][i];
         }else if(qual > q20){
             ++(this->cycleQ20Bases[bIndex][i]);
         }
         ++this->cycleBaseContents[bIndex][i];
         this->cycleBaseQual[bIndex][i] += (qual - 33);
         ++this->cycleTotalBase[i];
         this->cycleTotalQual[i] += (qual - 33);
         if(this->kmerLen){
             if(i < this->kmerLen - 1){
                 continue;
             }
             kmerVal = Evaluator::seq2int(seqStr, i - this->kmerLen + 1, this->kmerLen, kmerVal);
             if(kmerVal >= 0){
                 ++this->kmer[kmerVal];
             }
         }
     }
     if(this->overRepSampleFreq){
         if(this->reads % this->overRepSampleFreq == 0){
             std::set<int> steps = {10, 20, 40, 100, std::min(150, this->evaluatedSeqLen - 2)};
             for(auto& step: steps){
                 for(int j = 0; j < len - step; ++j){
                     std::string seq = seqStr.substr(j, step);
                     if(this->overRepSeq.count(seq) > 0){
                         ++this->overRepSeq[seq];
                         for(int p = j; p < seq.length() + j && p < this->evaluatedSeqLen; ++p){
                             ++this->overRepSeqDist[seq][p];
                         }
                         j += step;
                     }
                 }
             }
         }
     }
     ++this->reads;
 }
References Read::length(), Read::quality, Read::seq, Evaluator::seq2int(), and Seq::seqStr.
summarize()
void Stats::summarize (bool forced = false)
Summary statistic items, get this->bases, this->cycles, this->q20Bases, this->q30Bases, this->q20Total, this->q30Total, this->qualityCurves["mean"], this->qualityCurves["A/T/C/G/N"], this->contentCurves["A/T/C/G/N"], this->contentCurves["GC"] this->kmerMin, this->kmerMax, after summary, this->summarize will be set to true.
Parameters
forced forced to run summarize this->summarize will only run if (this->summarized is false) || (this->summarized is true && force = false)
Definition at line 130 of file stats.cpp.
{
     if(this->summarized && !forced){
         return;
     }
     // cycle and total bases
     bool getMinReadLen = false;
     int c = 0;
     for(c = 0; c < this->bufLen; ++c){
         this->bases += this->cycleTotalBase[c];
         if(!getMinReadLen && c > 1 && this->cycleTotalBase[c] < this->cycleTotalBase[c-1]){
             this->minReadLen = c;
             getMinReadLen = true;
         }
         if(this->cycleTotalBase[c] == 0){
             break;
         }
     }
     this->cycles = c;
     this->maxReadLen = c;
     // Q20, Q30, base content
     for(int i = 0; i < 8; ++i){
         for(int j = 0; j < this->cycles; ++j){
             this->q20Bases[i] += this->cycleQ20Bases[i][j];
             this->q30Bases[i] += this->cycleQ30Bases[i][j];
             this->baseContents[i] += this->cycleBaseContents[i][j];
         }
         this->q20Total += this->q20Bases[i];
         this->q30Total += this->q30Bases[i];
     }
     // quality curve for mean qual
     double* meanQualCurve = new double[this->cycles];
     std::memset(meanQualCurve, 0, sizeof(double) * this->cycles);
     for(int i = 0; i < this->cycles; ++i){
         meanQualCurve[i] = (double)this->cycleTotalQual[i] / (double)this->cycleTotalBase[i];
     }
     this->qualityCurves["mean"] = meanQualCurve;
     // quality curves and base contents curves for different nucleotides
     char nucleotides[5] = {'A', 'T', 'C', 'G', 'N'};
     for(int i = 0; i < 5; ++i){
         char b = nucleotides[i] & 0x07;
         double* qualCurve = new double[this->cycles];
         std::memset(qualCurve, 0, sizeof(double) * this->cycles);
         double* contentCurve = new double[this->cycles];
         std::memset(contentCurve, 0, sizeof(double) * this->cycles);
         for(int j = 0; j < this->cycles; ++j){
             if(this->cycleBaseContents[b][j] == 0){
                 qualCurve[j] = meanQualCurve[j];
             }else{
                 qualCurve[j] = (double)this->cycleBaseQual[b][j] / (double)this->cycleBaseContents[b][j];
             }
             contentCurve[j] = (double)this->cycleBaseContents[b][j] / (double)this->cycleTotalBase[j];
         }
         this->qualityCurves[std::string(1, nucleotides[i])] = qualCurve;
         this->contentCurves[std::string(1, nucleotides[i])] = contentCurve;
     }
     // GC content curve
     double* gcContentCurve = new double[this->cycles];
     std::memset(gcContentCurve, 0, sizeof(double) * this->cycles);
     char gIndex = 'G' & 0x07;
     char cIndex = 'C' & 0x07;
     for(int i = 0; i < this->cycles; ++i){
         gcContentCurve[i] = (double)(this->cycleBaseContents[gIndex][i] + this->cycleBaseContents[cIndex][i])/ (double)this->cycleTotalBase[i];
     }
     this->contentCurves["GC"] = gcContentCurve;
     if(this->kmerLen){
         // K-mer statistics
         this->kmerMin = this->kmer[0];
         this->kmerMax = this->kmer[0];
         for(int i = 1; i < this->kmerBufLen; ++i){
             this->kmerMin = std::min(this->kmer[i], this->kmerMin);
             this->kmerMax = std::max(this->kmer[i], this->kmerMax);
         }
     }
     this->summarized = true;
 }
Referenced by getBases(), getCycles(), getGCNumber(), getMaxBaseQual(), getMinBaseQual(), getMinReadLength(), getQ20(), getQ30(), getReads(), and merge().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const Stats & s) friend
output Stats object to std::ostream
Parameters
os std::ostream object
s Stats object
Returns
std::ostream object
Definition at line 347 of file stats.cpp.
{
     os << "total reads: " << s.reads << "\n";
     os << "total bases: " << s.bases << "\n";
     os << "Q20   bases: " << s.q20Total << "(" << (s.q20Total*100.0)/s.bases << "%)\n";
     os << "Q30   bases: " << s.q30Total << "(" << (s.q30Total*100.0)/s.bases << "%)\n";
     return os;
 }
The documentation for this class was generated from the following files:
stats.h
stats.cpp