UTIL: util Namespace Reference
util Namespace Reference
utility to operate on strings and directories
Functions
std::string basename (const std::string &path)
get the basename of a path string
char complement (char base)
get complement base of a nucleotide base
std::string dirname (const std::string &path)
get the dirname of a path string
bool ends_with (const std::string &str, const std::string &suf)
whether a string ends with some substring
void error_exit (const std::string &msg)
exit and print string to std::cerr
bool exists (const std::string &path)
check a file/directory exists or not
std::string get_alpha (const std::string &str)
remove non-alpha characters from a string
void get_valid (std::string &str, bool upper=false)
remove invalid sequence characters from a string
int hamming (const std::string &str1, const std::string &str2)
get hamming distance of two strings
bool isdir (const std::string &path)
check a string is a directory or not
bool isfile (const std::string &path)
check a string is a regular file or not
std::string joinpath (const std::string &dirname, const std::string &basename)
join dirname and basename into a path
std::string lstrip (const std::string &str)
get rid of the left leading white space characters of a string
bool makedir (const std::string &path)
make directories recursively
char num2qual (int num)
convert number to 33 based score character
std::string replace (const std::string &str, const std::string &pat, const std::string &des)
replace a substr apearing in a string with another string
std::string reverse (const std::string &str)
get a reverse sequence of str
std::string rstrip (const std::string &str)
get rid of the trailling white space characters of a string
void split (const std::string &str, std::vector< std::string > &vec, std::string sep=" ")
split a string by predefined seperator into a vector
bool starts_with (const std::string &str, const std::string &pre)
whether a string starts with some substring
void str2lower (std::string &str)
make a string each character lowercased
void str2upper (std::string &str)
make a string each character uppercased
std::string strip (const std::string &str)
get rid of the leading and ending white space characters of a string
Detailed Description
utility to operate on strings and directories
Function Documentation
basename()
std::string util::basename (const std::string & path) inline
get the basename of a path string
Parameters
path name
Returns
basename of path
Definition at line 138 of file util.h.
{
         std::string fpath = util::replace(path, "~", std::string(std::getenv("HOME")) + "/");
         if(fpath.find_first_of(" \t\n\v\f\r") != std::string::npos){
             return "";
         }
         std::string::size_type pos1 = fpath.find_last_of("/\\");
         if(pos1 == std::string::npos){
             return fpath;
         }
         std::string::size_type pos2 = fpath.find_last_not_of("/\\");
         if(pos2 == fpath.size() - 1){
             return fpath.substr(pos1 + 1, pos2 - pos1);
         }
         std::string::size_type pos3 = fpath.find_last_of("/\\", pos2);
         if(pos3 == std::string::npos){
             return fpath.substr(0, pos2 + 1);
         }
         return fpath.substr(pos3 + 1, pos2 - pos3);
     }
References replace().
Referenced by joinpath().
complement()
char util::complement (char base) inline
get complement base of a nucleotide base
Parameters
base nucleotide base character
Returns
the uppercased complementary nucleotide base
Definition at line 369 of file util.h.
{
         switch(base){
             case 'A': case 'a':
                 return 'T';
             case 'T': case 't':
                 return 'A';
             case 'C': case 'c':
                 return 'G';
             case 'G': case 'g':
                 return 'C';
             default:
                 return 'N';
         }
     }
dirname()
std::string util::dirname (const std::string & path) inline
get the dirname of a path string
Parameters
path name
Returns
dirname of path
Definition at line 162 of file util.h.
{
         std::string fpath = util::replace(path, "~", std::string(std::getenv("HOME")) + "/");
         std::string::size_type pos = fpath.find_last_of("/\\");
         if(pos == std::string::npos){
 #ifdef _WIN32
             return ".\\";
 #else
             return "./";
 #endif
         }
         if(pos == fpath.size() - 1){
             std::string::size_type pos1 = fpath.find_last_not_of("/\\");
             if(pos1 == std::string::npos){
 #ifdef _WIN32
                 return "\\";
 #else
                 return "/";
 #endif
             }
             std::string::size_type pos2 = fpath.find_last_of("/\\", pos1);
             if(pos2 == std::string::npos){
 #ifdef _WIN32
                 return ".\\";
 #else
                 return "./";
 #endif
             }else{
                 return fpath.substr(0, pos2 + 1);
             }
         }else{
             return fpath.substr(0, pos + 1);
         }
     }
References replace().
Referenced by joinpath(), and makedir().
ends_with()
bool util::ends_with (const std::string & str, const std::string & suf) inline
whether a string ends with some substring
Parameters
str whole string
suf substring
Returns
true if str ends with suf
Definition at line 34 of file util.h.
{
         if(str.length() < suf.length()){
             return false;
         }else{
             return std::equal(suf.rbegin(), suf.rend(), str.rbegin());
         }
     }
Referenced by Writer::init(), FqReader::isfq(), and FqReader::isZippedFq().
error_exit()
void util::error_exit (const std::string & msg) inline
exit and print string to std::cerr
Parameters
msg string to print to std::cerr
Definition at line 360 of file util.h.
{
         std::cerr << "ERROR: " << msg << std::endl;
         exit(-1);
     }
exists()
bool util::exists (const std::string & path) inline
check a file/directory exists or not
Parameters
path string of a file/directory
Returns
true if path exists
Definition at line 253 of file util.h.
{
         return util::isdir(path) || util::isfile(path);
     }
References isdir(), and isfile().
get_alpha()
std::string util::get_alpha (const std::string & str) inline
remove non-alpha characters from a string
Parameters
str string to be filtered
Returns
a string without non-alpha characters
Definition at line 295 of file util.h.
{
         std::string ret;
         std::copy_if(str.cbegin(), str.cend(), std::back_inserter(ret), (int(*)(int))std::isalpha);
         return ret;
     }
get_valid()
void util::get_valid (std::string & str, bool upper = false) inline
remove invalid sequence characters from a string
Parameters
str string to be filtered
upper convert result to uppercase if true
Definition at line 305 of file util.h.
{
         size_t total = 0;
         for(size_t i = 0; i < str.size(); ++i){
             if(std::isalpha(str[i]) || str[i] == '-' || str[i] == '*'){
                 str[total++] = (upper ? std::toupper(str[i]) : str[i]);
             }
         }
         str.resize(total);
     }
hamming()
int util::hamming (const std::string & str1, const std::string & str2) inline
get hamming distance of two strings
Parameters
str1 string 1
str2 string 2
Returns
hamming distance of string 1 and string 2
Definition at line 334 of file util.h.
{
         int diff = std::abs((int)(str1.size() - str2.size()));
         for(int i = 0; i < std::min(str1.size(), str2.size()); ++i){
             diff += (str1[i] == str2[i] ? 0 : 1);
         }
         return diff;
     }
isdir()
bool util::isdir (const std::string & path) inline
check a string is a directory or not
Parameters
path string of a file/directory
Returns
true if path is an existing path
Definition at line 233 of file util.h.
{
 #ifdef _WIN32
         struct _stat info;
         if(_stat(path.c_str(), &info) != 0){
             return false;
         }
         return (info.st_mode & _S_IFDIR);
 #else
         struct stat info;
         if(stat(path.c_str(), &info) != 0){
             return false;
         }
         return (info.st_mode & S_IFDIR);
 #endif
     }
Referenced by exists(), and makedir().
isfile()
bool util::isfile (const std::string & path) inline
check a string is a regular file or not
Parameters
path string of a file/directory
Returns
true if path is an existing regular file
Definition at line 213 of file util.h.
{
 #ifdef _WIN32
         struct _stat info;
         if(_stat(path.c_str(), &info) != 0){
             return false;
         }
         return (info.st_mode & _S_IFREG);
 #else
         struct stat info;
         if(stat(path.c_str(), &info) !=0){
             return false;
         }
         return (info.st_mode & S_IFREG);
 #endif
     }
Referenced by exists().
joinpath()
std::string util::joinpath (const std::string & dirname, const std::string & basename) inline
join dirname and basename into a path
Parameters
dirname dirname of the path
basename basename of the path
Returns
full path
Definition at line 201 of file util.h.
{
 #ifdef _WIN32
         return dirname + "\\" + basename;
 #else
         return dirname + "/" + basename;
 #endif
     }
References basename(), and dirname().
lstrip()
std::string util::lstrip (const std::string & str) inline
get rid of the left leading white space characters of a string
Parameters
str string to be stripped from front
Returns
a string with left leading white spaces stripped
Definition at line 63 of file util.h.
{
         std::string::size_type pos = str.find_first_not_of(" \t\n\v\f\r");
         if(pos == std::string::npos){
             return "";
         }
         return str.substr(pos);
     }
makedir()
bool util::makedir (const std::string & path) inline
make directories recursively
Parameters
path path of directory to be created
Returns
true if make directories successfully
Definition at line 261 of file util.h.
{
         std::string fpath = util::replace(path, "~", std::string(std::getenv("HOME")) + "/");
 #ifdef _WIN32
         int ret = _mkdir(fpath.c_str());
 #else
         mode_t mode = 0755;
         int ret = mkdir(fpath.c_str(), mode);
 #endif
         if(ret == 0){
             return true;
         }
         switch(errno){
             case ENOENT:
                 {
                     if(!util::makedir(util::dirname(fpath))){
                         return false;
                     }
                 }
 #ifdef _WIN32
                 return 0 == _mkdir(fpath.c_str());
 #else
                 return 0 == mkdir(fpath.c_str(), mode);
 #endif
             case EEXIST:
                 return util::isdir(fpath);
             default:
                 return false;
         }
     }
References dirname(), isdir(), and replace().
num2qual()
char util::num2qual (int num) inline
convert number to 33 based score character
Parameters
num number of score
Returns
33 based score character
Definition at line 346 of file util.h.
{
         if(num > 127 - 33){
             num = 127 - 33;
         }
         if(num < 0){
             num = 0;
         }
         char c = num + 33;
         return c;
     }
replace()
std::string util::replace (const std::string & str, const std::string & pat, const std::string & des) inline
replace a substr apearing in a string with another string
Parameters
str string
pat substr of string to be replaced
des string to be used to replaced with pat
Returns
a string with each pat replaced by des
Definition at line 109 of file util.h.
{
         std::string ret;
         std::string::size_type las = 0, cur = 0;
         while((cur = str.find(pat, cur)) != std::string::npos){
             ret.append(str.substr(las, cur - las));
             ret.append(des);
             cur += pat.length();
             las = cur;
         }
         if(las != std::string::npos){
             ret.append(str.substr(las));
         }
         return ret;
     }
Referenced by basename(), dirname(), makedir(), Stats::reportHtmlContents(), Stats::reportHtmlKmer(), Stats::reportHtmlORA(), and Stats::reportHtmlQuality().
reverse()
std::string util::reverse (const std::string & str) inline
get a reverse sequence of str
Parameters
str input string sequence
Returns
reverse sequence of str
Definition at line 128 of file util.h.
{
         std::string ret = str;
         std::reverse(ret.begin(), ret.end());
         return ret;
     }
rstrip()
std::string util::rstrip (const std::string & str) inline
get rid of the trailling white space characters of a string
Parameters
str string to be stripped from back
Returns
a string with right ending white spaces stripped
Definition at line 75 of file util.h.
{
         std::string::size_type pos = str.find_last_not_of(" \t\n\v\f\r");
         if(pos == std::string::npos){
            return "";
         }
         return str.substr(0, pos + 1);
     }
split()
void util::split (const std::string & str, std::vector< std::string > & vec, std::string sep = " ") inline
split a string by predefined seperator into a vector
Parameters
str string
vec vector to store the split results
sep seperators, can contain a series of seperators
Definition at line 88 of file util.h.
{
         std::string::size_type las, cur;
         las = cur = str.find_first_not_of(sep);
         while((las = str.find_first_not_of(sep, las)) != std::string::npos){
             cur = str.find_first_of(sep, las);
             if(cur != std::string::npos){
                 vec.push_back(str.substr(las, cur - las));
             }else{
                 vec.push_back(str.substr(las));
                 break;
             }
             las = cur;
         }
     }
starts_with()
bool util::starts_with (const std::string & str, const std::string & pre) inline
whether a string starts with some substring
Parameters
str whole string
pre substring
Returns
true if str starts with pre
Definition at line 21 of file util.h.
{
         if(str.length() < pre.length()){
             return false;
         }else{
             return std::equal(pre.begin(), pre.end(), str.begin());
         }
     }
str2lower()
void util::str2lower (std::string & str) inline
make a string each character lowercased
Parameters
str string to be lowercased
Definition at line 325 of file util.h.
{
         std::transform(str.begin(), str.end(), str.begin(), (int (*)(int))std::tolower);
     }
str2upper()
void util::str2upper (std::string & str) inline
make a string each character uppercased
Parameters
str string to be uppercased
Definition at line 318 of file util.h.
{
         std::transform(str.begin(), str.end(), str.begin(), (int (*)(int))std::toupper);
     }
strip()
std::string util::strip (const std::string & str) inline
get rid of the leading and ending white space characters of a string
Parameters
str string to be stripped in both ends
Returns
a string with white spaces stripped in both ends
Definition at line 46 of file util.h.
{
         std::string::size_type ipos = str.find_first_not_of(" \t\n\v\f\r");
         if(ipos == std::string::npos){
             return "";
         }
         std::string::size_type epos = str.find_last_not_of(" \t\n\v\f\r");
         if(epos == ipos){
             return str.substr(ipos);
         }else{
             return str.substr(ipos, epos - ipos + 1);
         }
     }