UTIL: htmlutil Namespace Reference
htmlutil Namespace Reference
some useful utilities for html output
Functions
std::string formatNumber (const size_t &number)
format a big number with KMGTP units
template<typename T >
void outputTableRow (std::ofstream &ofs, const std::string &key, T val)
output a row with two columns as a html table row to ofstream
Detailed Description
some useful utilities for html output
Function Documentation
formatNumber()
std::string htmlutil::formatNumber (const size_t & number) inline
format a big number with KMGTP units
Parameters
number a non-negative number to be formatted
Returns
formatted number string
Definition at line 27 of file htmlutil.h.
{
         double num = (double)number;
         const std::string unit[6] = {"", "K", "M", "G", "T", "P"};
         int order = 0;
         while(number > 1000.0){
             order += 1;
             num /= 1000.0;
         }
         return std::to_string(num) + " " + unit[order];
     }
Referenced by FilterResult::reportHtmlBasic().
outputTableRow()
template<typename T > void htmlutil::outputTableRow (std::ofstream & ofs, const std::string & key, T val)
output a row with two columns as a html table row to ofstream
Parameters
ofs std::ofstream to output to
key first field of a row
val second field of a row
Definition at line 17 of file htmlutil.h.
{
         std::stringstream ss;
         ss << val;
         ofs << "<tr><td class='col1'>" + key + "</td><td class='col2'>" + ss.str() + "</td></tr>\n";
     }
Referenced by FilterResult::reportAdaptersHtmlDetails(), and FilterResult::reportHtmlBasic().